# 1. Builder 단계: Gradle을 사용해 빌드 # 첫 번째 스테이지 (빌드)
FROM gradle:7.5.1-jdk11 as builder 
WORKDIR /workspace/app

COPY . /workspace/app/

RUN ./gradlew build -p membership-service  # 빌드 수행

# 2. Runtime 단계: 빌드 결과물을 가져와서 Java 11로 실행 
## 두 번째 스테이지 (런타임)
FROM openjdk:11-jre-slim  
WORKDIR /workspace/app

# 빌드된 jar 파일 복사
COPY --from=builder /workspace/app/membership-service/build/libs/membership-service-1.0.0.jar .  

EXPOSE 8080

ENTRYPOINT ["java", "-jar", "membership-service-1.0.0.jar"]
