name: Membership Service - DEV

env:
  MODULE: membership-service
  
on:
  push:
    branches: [ "devops2" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.DEV_AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.DEV_AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-northeast-2
        
    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2

    - name: Build, tag, and push Docker image to Amazon ECR
      env:
        REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        REPOSITORY: membership-service-devops
        IMAGE_TAG: ${{ github.sha }}
      run: |
        envsubst < Dockerfile.template | docker build -t $REGISTRY/$REPOSITORY:$IMAGE_TAG -f - .
        docker push $REGISTRY/$REPOSITORY:$IMAGE_TAG

    - name: Checkout Helm Repository
      uses: actions/checkout@v4
      with:
        reposiroty: heoseongh/kitri_final_helm
        path: helm-chart
        ref: main